"""
This module's purpose is to expose a function `get_bateman_video()` that takes in a youtube video URL, generates the upload-able
bateman video, and returns the file path to that video.
"""

from pathlib import Path
import subprocess
from typing import TypedDict

from app.config import console
from app.youtube.utils import find_hottest_segment
from app.youtube.thumbnail import get_yt_thumbnail
from app.youtube.download import download_song_youtube


class BatemanVideoArtifacts(TypedDict):
    audio_path: Path | str
    thumbnail_path: Path
    video_only_path: Path
    final_video_path: Path
    delay_in_seconds: int


def generate_video(bg_image_path: Path) -> Path:
    """
    Generate patrick bateman walking to music video using the given background image. Also shows a progress bar.

    Args:
        bg_image_path (str): path to the background image  (cover art)

    Returns:
        str: path to the output video
    """
    console.print(f"Generating video using thumbnail [bold]{bg_image_path}[/bold]")
    with console.status("Generating Video", spinner="dots"):
        result = subprocess.run(
            ["app/scripts/generateVideoYoutube.sh", str(bg_image_path)],
            capture_output=True,
        )
        # print("generate stdout: ", result.stdout)
        # print("generate stderr: ", result.stderr)
        output_video_path = str(result.stdout).lstrip("b'").rstrip("\\n'")
    console.print(f"output video path (only video): [bold]{output_video_path}[/bold]")
    return Path(output_video_path)


def combine_audio_video(
    video_path: Path, audio_path: Path, delay_in_seconds: int
) -> Path:
    """
    Combines the given audio and video with delay added from start of the audio.

    Args:
        video_path (Path): path to the video
        audio_path (Path): path to the audio

    Returns:
        Path: final output video path
    """
    console.print(
        f"Combining video [bold]{video_path}[/bold] with audio [bold]{audio_path}[/bold] (delay: [bold]{delay_in_seconds}s[/bold])"
    )
    result = subprocess.run(
        [
            "app/scripts/combineAudioVideo.sh",
            audio_path,
            video_path,
            str(delay_in_seconds),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    # print("combine stdout: ", result.stdout)
    # print("combine stderr: ", result.stderr)
    final_video_path = result.stdout.strip()
    console.print(f"final output path (with audio): [b]{final_video_path}[/b]")
    return Path(final_video_path)


def get_bateman_video(url: str) -> Path:
    """
    Generates a video of Patrick Bateman walking to the music of the given spotify track URL. The video is generated by combining the cover art of the track and the 30-second preview of the track. The video is generated using the generateVideoSpotify.sh script and the audio is combined with the video using the combineAudioVideo.sh script. The final video is saved in the assets folder.

    Args:
        url (str): spotify URL of the song

    Returns:
        str : path to the final output video.
    """
    console.print(f"Preparing bateman video for [bold]{url}[/bold]")
    artifacts = build_bateman_video(url)
    return artifacts["final_video_path"]


def build_bateman_video(url: str) -> BatemanVideoArtifacts:
    song_data = download_song_youtube(url)
    bg_image_path = song_data.get("thumbnail_path") or get_yt_thumbnail(url)
    audio_path = song_data["audio_path"]
    heatmap = song_data["heatmap"]

    console.print(
        f"[bold #FFC0CB]audio-path     :[/bold #FFC0CB] [#DDA0DD]{audio_path}[/#DDA0DD]"
    )
    console.print(
        f"[bold #FFC0CB]thumbnail-path :[/bold #FFC0CB] [#DDA0DD]{bg_image_path}[/#DDA0DD]"
    )

    if heatmap is not None:
        console.print(
            f"Heatmap data found: [bold]{len(heatmap)}[/bold] segments. Selecting the hottest 30-second window"
        )
        hottest_segment = find_hottest_segment(heatmap)
        delay_in_seconds = int(hottest_segment["start_time"])
        console.print(
            f"Using hottest segment from [bold]{hottest_segment['start_time']:.2f}s[/bold] to [bold]{hottest_segment['end_time']:.2f}s[/bold]"
        )
    else:
        console.print(
            "No heatmap data found. Falling back to [bold]0s[/bold] audio delay"
        )
        delay_in_seconds = 0
    video_path = generate_video(bg_image_path)
    final_video_path = combine_audio_video(video_path, audio_path, delay_in_seconds)
    return {
        "audio_path": audio_path,
        "thumbnail_path": bg_image_path,
        "video_only_path": video_path,
        "final_video_path": Path(final_video_path),
        "delay_in_seconds": delay_in_seconds,
    }


if __name__ == "__main__":
    get_bateman_video("https://www.youtube.com/watch?v=BjC0KUxiMhc")
